### ISSUE TITLE
Hard crash from using the "Dollar" option in plugin

### ISSUE THREAD

**Issue by ghost** [litui/dtmf_dolphin#10]
Hello,

I was going through testing the nickel, dime, quarter, and finally dollar options in this plugin (Redbox US).  I was able to hear the tones for the first three, then when selecting and playing the dollar option my device powered off.  I am unable to restart it, do not see any power indication when plugging it into USB, and tried the OK+back button reset by holding for 30 seconds to no avail.

Any thoughts?

**edit**
I was able to hold the left key+back for 30+ seconds and the device rebooted, stating that it had crashed.  I tried the same process after the reboot and the device didn't crash again.  May have been user error or dumb luck.

Please feel free to ask any questions if you're interested, otherwise please feel free to close.

Thank you.

**Comment by litui** [comment]
Huh, fascinating. No, can't say I've encountered this. What firmware are (were) you running? Definitely reach out to Flipper Devices.

**Comment by ghost** [comment]
I am running the /RogueMaster/flipperzero-firmware-wPlugins firmware.

**Comment by litui** [comment]
Thanks for the update. Closing.
