### ISSUE TITLE
Misc menu give nothing..

### ISSUE THREAD

**Issue by Foul** [litui/dtmf_dolphin#4]
when clicking on Misc... nothing happen !?

I'm on latest RogueMaster firmware.

**Comment by ankris812** [comment]
same with unleashed

**Comment by litui** [comment]
I haven't finished fleshing out the Misc menu folks. Sorry for the inconvenience. I'll try to get it working.

For future reference, I don't control the RogueMaster/Unleashed forks of dtmf_dolphin. Only this repository.

**Comment by litui** [comment]
Fixed in 5e8e55908933a7f46a31652ac9705c81bfe15316.
