### ISSUE TITLE
2600 not recognised

### ISSUE THREAD

**Issue by Geddeon** [litui/dtmf_dolphin#8]
I have called to [Project MF](http://www.projectmf.org/) station and it didn't pick the 2600 tone from Flipper.
Not sure if the mobile network compressed it or anything else went wrong.

**Comment by litui** [comment]
It's likely related to #6. The tones coming out of it just aren't actual sines. Also as noted in the readme, the 2600 tone is off by a few Hz due to the sample rate.

**Comment by litui** [comment]
Closing issue. It's known that the approach is imperfect.
